apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust
    role: master
  type: NodePort

  ports:
    - protocol: TCP
      name: locust-web
      port: 8089
      targetPort: 8089
    - protocol: TCP
      name: locust-master
      port: 5557
      targetPort: 5557

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      initContainers:
        - name: download-locustfile
          image: busybox
          command: ["wget", "-O", "/mnt/locust/locustfile.py", "https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/src/loadgenerator/locustfile.py"]
          volumeMounts:
            - name: locust-files
              mountPath: /mnt/locust
      containers:
        - name: locust
          image: locustio/locust:latest
          command: 
            - "/bin/bash"
            - "-c"
            - "pip install Faker && locust -f /mnt/locust/locustfile.py --master -H http://locust-master:8089 --host http://frontend.learning"
          # command: [sleep, "3600"]
          ports:
            - containerPort: 8089
            - containerPort: 5557
          volumeMounts:
            - name: locust-files
              mountPath: /mnt/locust
      volumes:
        - name: locust-files
          emptyDir: {}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: master1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      initContainers:
        - name: download-locustfile
          image: busybox
          command: ["wget", "-O", "/mnt/locust/locustfile.py", "https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/src/loadgenerator/locustfile.py"]
          volumeMounts:
            - name: locust-files
              mountPath: /mnt/locust
      containers:
        - name: locust
          image: locustio/locust:latest
          command: 
            - "/bin/bash"
            - "-c"
            - "pip install Faker && locust -f /mnt/locust/locustfile.py --worker --master-host locust-master"
          volumeMounts:
            - name: locust-files
              mountPath: /mnt/locust
      volumes:
        - name: locust-files
          emptyDir: {}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: master1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-exporter
spec:
  selector:
    matchLabels:
      app: locust-exporter
  template:
    metadata:
      labels:
        app: locust-exporter
    spec:
      containers:
      - name: locust-exporter
        image: containersol/locust_exporter
        env:
        - name: LOCUST_EXPORTER_URI
          value: "http://locust-master:8089"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9646
---
apiVersion: v1
kind: Service
metadata:
  name: locust-exporter
spec:
  selector:
    app: locust-exporter
  ports:
  - port: 9646
    targetPort: 9646


